### ISSUE TITLE
Move the code for the tab-box and action-button serverside

### ISSUE THREAD

**Issue by tanho63** [r4ds/mentordash#35]
It may be helpful to move these server-side and place a `req( {slack_token} )` inside it, and then create a modal to prompt for slack login if slack_token is not found

**Comment by jonthegeek** [comment]
Yeah, my work shiny apps end up being pretty much entirely server-side. I'm going to sort out what to show before login and after. I'm CONSIDERING only having the "Sign in with Slack" button if we don't have a token for you, and then the "normal" app if we do (MAYBE with a sign out button to clear the cookie, but probably not even that). What do you think?

**Comment by tanho63** [comment]
Yeah, I doubt a signout/clear-cookie button is even necessary, maybe as a feature add for later. 

A modal popup for logging in if no token and otherwise just hiding all auth features is pretty close to enough imo
