### ISSUE TITLE
Count octagonal_sign as done

### ISSUE THREAD

**Issue by jonthegeek** [r4ds/mentordash#44]
As a data nerd, I'd like to be able to differentiate between "answered" questions and "questions where the asker explicitly walked away without ever giving enough info to answer the question," so that I can predict things eventually.

We've added :octagonal_sign: as a "closed" tag for questions. Treat those the same as checks and threads.

**Comment by tanho63** [comment]
Maybe worth considering a “friendlier-looking emoji”? Can upload new custom emotes with “close-question”, “expired” etc as the name?

**Comment by jonthegeek** [comment]
Excellent point. I think I'll do that.
